### ISSUE TITLE
Request to omit all statements on csarven.ca

### ISSUE THREAD

**Issue by csarven** [snarfed/indie-map#2]
Hi. I'm the current owner of [csarven.ca](http://csarven.ca/). I would appreciate it if the dataset, map, and anything else, can omit all statements pertaining to csarven.ca. If there is any information that's currently on csarven.ca that the crawler is discovering, please let me know, I can remove those. Same goes for any other place that I might have access to. Thanks.

**Comment by snarfed** [comment]
oh wow, hey @csarven. apologies, i totally missed this. absolutely, will do.

**Comment by snarfed** [comment]
done! your site is now gone from the dataset. [details.](https://github.com/snarfed/indie-map#removing-a-site)

fwiw, here's what i see in http://csarven.ca/robots.txt right now. i do get that you may want to allow some crawlers but not others, like indie map.

```
User-agent: *
Disallow: /archives
Disallow: /scripts
Disallow: /url
Disallow: /labs
Disallow: /presentations
Disallow: /webstream
Disallow: /search
Disallow: /statistical-linked-dataspaces-and-analysis-overview
Allow: /labs/indexability
Allow: /archives/articles
```

**Comment by csarven** [comment]
Thanks!

Pardon me if I'm looking at the wrong code, but perhaps it is also worthwhile to update the `user-agent` value: https://github.com/snarfed/indie-map/blob/master/crawl/wget.sh#L9 ?

**Comment by csarven** [comment]
I would classify indie-map (the software of this repository) as the user-agent, as opposed to a particular library that's doing the fetching. Just as Firefox uses its own library to negotiate resources. But yes, generally it can be arbitrary.

So, you can do something like `User-Agent: indie-map` or if you're feeling adventurous use `User-Agent: https://github.com/snarfed/indie-map/` or some other HTTP URI that can provide a structured definition for the application eg view-source https://dokie.li/

**Comment by snarfed** [comment]
also fwiw, i've only actually done this whole crawl once, and i have no plans to do it again right now, regularly or not.

still, good idea. thanks for the nudge.
